- hosts: 192.168.29.212
  vars_files: 
           lock.yml
  tasks:
    - name: Adding docker repositories
      yum_repository:
        name: docker-ce
        description: docker_ce
        file: docker_repo
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no
    - name: intalling python
      package:
            name: python36
            state: present
    - name: installing python library 
      pip:
         name: docker-py
    - name: installing docker-ce
      package: 
          name: "docker-ce-18.09.1-3.el7.x86_64"
          state: present
      register: x
    - debug:
         var: x
    - name: Installing Docker SDK for python3
      command: pip3 install docker 
    - name: Starting docker
      service: 
       name: docker
       state: started
       enabled: yes
    - name: Log into DockerHub
      docker_login:
           username: "{{user}}"
           password: "{{pass}}"
    - name: pull an image
      docker_image:
          name: httpd
          source: pull 
    - name: Creating folder and copying html file...
      file:
          path: webpages
          state: directory
    - name: COPYING CODE FILE TO MANAGED NODE
      copy: 
        src: /root/test.html
        dest: /webpages/
    - name: Creating container using HTTPD Image 
      docker_container:
            name: MyWebServer
            image: httpd
            state: started
            exposed_ports:
                — "80"
            ports: 
                - "8080:80"
            volumes:
                - /webpages:/usr/local/apache2/htdocs/
      ignore_errors: True
    
